import{a as m,S as b,i as l}from"./assets/vendor-6e0bf343.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const h of r.addedNodes)h.tagName==="LINK"&&h.rel==="modulepreload"&&a(h)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();m.defaults.baseURL="https://pixabay.com";const f=15,y=async(s,e)=>{const a={q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",key:"43337272-ad726c9b9e29498af38112cb0",page:e,per_page:f};return await m.get("/api/",{params:a})};function p(s){return s.map(e=>`
      <div class="card-wrapper">
  <li class="gallery-card">
    <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}" class="gallery-img"/></a>
    <div class="gallery-panel">
      <p>Likes ${e.likes}</p>
      <p>Views ${e.views}</p>
      <p>Comments ${e.comments}</p>
      <p>Downloads ${e.downloads}</p>
    </div>
  </li>
</div>
    `).join("")}const g=document.querySelector(".js-form"),d=document.querySelector(".js-gallery"),i=document.querySelector(".loader"),c=document.querySelector(".load-more"),L=new b(".gallery a",{captionsresponse:"alt",captionDelay:250});let n=1,u=null;async function w(s){if(s.preventDefault(),u=s.target.elements.search.value.trim(),d.innerHTML="",n=1,c.classList.add("is-hidden"),i.classList.remove("is-hidden"),g.reset(),u==="")return i.classList.add("is-hidden"),l.error({message:"The input field must not be empty!",position:"topRight"});try{const{data:{totalHits:e,hits:o}}=await y(u,n);if(o.length===0)return i.classList.add("is-hidden"),l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});if(e<f)return i.classList.add("is-hidden"),d.innerHTML=p(o),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"});c.classList.remove("is-hidden"),d.innerHTML=p(o),L.refresh(),i.classList.add("is-hidden")}catch(e){console.log(e)}}g.addEventListener("submit",w);async function v(s){try{n++;const{data:{totalHits:e,hits:o}}=await y(u,n);d.insertAdjacentHTML("beforeend",p(o)),L.refresh();const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();if(window.scrollBy({top:a*2,behavior:"smooth"}),Math.ceil(e/f)===n)return c.classList.add("is-hidden"),c.removeEventListener("click",v),l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){console.log(e)}}c.addEventListener("click",v);
//# sourceMappingURL=commonHelpers.js.map
